site_name: MachInNav Engine
repo_name: MachInNav Engine
docs_dir: docs
site_description: 'MachInNav Engine is a powerful and easy-to-use indoor navigation engine for Android.'
theme:
    name: material
    palette:
        - scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
          primary: black
          accent: light blue
        - scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
          primary: black
          accent:  cyan
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: images/location.png

    favicon: images/favicon.ico
    search: true
    features:
      - toc.integrate
      - header.title
      - header.autohide
      - navigation.tabs
      - navigation.sections
      - navigation.top
      - navigation.footer
      - navigation.tracking
      - navigation.scrollspy
      - search.suggest
      - search.highlight
      - search.loader
      - search.share
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
      - footer
    language: en
nav:
    - Home: index.md
    - Getting Started:
          - 'Introduction': getting-started/introduction.md
          - 'Android Studio Setup': getting-started/android-studio-setup.md
          - 'Gradle Setup': getting-started/gradle-setup.md

    - 'API Reference': https://indoor-navigation-lib.bitbucket.io/
    - 'User Guide':
          - 'User Guide': user-guide/user-guide.md
          - 'User Guide': user-guide/user-guide.md
    - 'Contributing':
          - 'Contributing': contributing/contributing.md
          - 'Contributing': contributing/contributing.md
    - 'About':
          - 'About': about/about.md
          - 'About': about/about.md
copyright: |
  &copy; 2024 <a href="https://github.com/kvrae"  target="_blank" rel="opener">Karam Mannai</a>

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji
  - toc:
      permalink: true
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kvrae
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/karam-mannai/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC9z3z3YX6J5J3b3Z
    - icon: fontawesome/brands/medium
      link: https://medium.com/@karammannai