site_name: MachInNav Engine
repo_name: MachInNav Engine
site_description: 'MachInNav Engine is a powerful and easy-to-use indoor navigation engine for Android.'
site_author: Karam Mannai
repo_url: https://github.com/KvRae/docs-generation
docs_dir: docs
theme:
    name: material
    palette:
        - scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
          primary: white
          accent: light blue
        - scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
          primary: black
          accent:  cyan
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: images/location.png
    favicon: images/favicon.ico
    search: true
    features:
      - toc.integrate
      - header.title
      - header.autohide
      - navigation.tabs
      - navigation.sections
      - navigation.top
      - navigation.footer
      - navigation.tracking
      - navigation.scrollspy
      - search.suggest
      - search.highlight
      - search.loader
      - search.share
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
      - footer
    language: en
nav:
    - Home: index.md
    - Getting Started:
        - Installation: getting_started/installation.md
        - Quick Start: getting_started/quick_start.md
        - Usage: getting_started/usage.md
        - Youtube Tutorials 🡕 : https://www.youtube.com/@kvrae8698/featured
    - Features:
        - Features Overview: features/features_overview.md
        - Navigation: features/navigation.md
        - Map Loading: features/map_loading.md
        - Localization: features/localization.md
        - Path Finding: features/path_finding.md
        - Theme Customization: features/theme_customization.md
    - API Reference:
        - API Overview: api_reference/api_overview.md
        - Library: api_reference/library.md
        - SceneView: api_reference/scene_view.md
        - Filament: api_reference/filament.md

    - Release Notes: release_notes.md
    - Support:
        - FAQ: support/faq.md
        - Troubleshooting: support/troubleshooting.md
        - Contact Us: support/contact_us.md
copyright: |
  &copy; 2024 <a href="https://github.com/kvrae"  target="_blank" rel="opener">Karam Mannai</a>

plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji
  - toc:
      permalink: true
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kvrae
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/karam-mannai/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCb_lwSmYhnGBD5JH6BXYkvQ
    - icon: fontawesome/brands/medium
      link: https://medium.com/@karammannai